name: ArmorSlots
main: net.pwncraft.kaikz.armorslots.ArmorSlots
version: 1.4
commands:
  hat:
    description: Sets the item in your hand to your head.
    usage: /<command>
  chestplate:
    description: Sets the item in your hand to your chestplate.
    usage: /<command>
  leggings:
    description: Sets the item in your hand to your leggings.
    usage: /<command>
  boots:
    description: Sets the item in your hand to your boots.
    usage: /<command>
  firearmor:
    description: Looks as if you're on fire.
    usage: /<command>