name: ArmorSlots
author: Kaikz
website: http://freeplaynz.me
description: Store blocks in armor slots. 
main: me.freeplaynz.armorslots.ArmorSlots
version: 1.7
commands:
  hat:
    description: Sets the item in your hand to your head.
    usage: /<command>
  chestplate:
    description: Sets the item in your hand to your chestplate.
    usage: /<command>
  leggings:
    description: Sets the item in your hand to your leggings.
    usage: /<command>
  boots:
    description: Sets the item in your hand to your boots.
    usage: /<command>
  armor:
    description: Base command for setting armor.
    usage: /<command>